// <auto-generated />
using System;
using DashTelecom.Infrastructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DashTelecom.Api.Migrations
{
    [DbContext(typeof(MeuDbContext))]
    [Migration("20220328174927_DbModelo")]
    partial class DbModelo
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DashTelecom.Domain.Models.TabTelecomConsolidado", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Bilhetado")
                        .HasColumnType("int");

                    b.Property<string>("Classe")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<decimal>("Custo")
                        .HasColumnType("decimal ");

                    b.Property<DateTime>("Dia")
                        .HasColumnType("DateTime");

                    b.Property<int>("Disparos")
                        .HasColumnType("int");

                    b.Property<int>("DisparosTarifados")
                        .HasColumnType("int");

                    b.Property<int>("Fila")
                        .HasColumnType("int");

                    b.Property<int>("Maior30")
                        .HasColumnType("int");

                    b.Property<int>("Menor30")
                        .HasColumnType("int");

                    b.Property<string>("Servidor")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("StatusFinal")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("StatusInicial")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Terminator")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("TabTelecomConsolidado");
                });

            modelBuilder.Entity("DashTelecom.Domain.Models.TabTelecomOperadoras", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Operadora")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Operadora_ftr")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Pag_sub")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Rota")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Tecnologia")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("TabTelecomOperadoras");
                });
#pragma warning restore 612, 618
        }
    }
}
